from pathlib import Path
import re
p=Path('index.html')
s=p.read_text(encoding='utf-8')
start=s.find('<section class="play" id="play">')
if start<0: start=s.find('<section class="play">')
if start<0: raise SystemExit('play section not found')
end=s.find('</section>',start)
if end<0: raise SystemExit('play section end not found')
section=s[start:end+10]
marker='<div class="card"><h4>Grid Generator</h4>'
m=section.find(marker)
if m<0: raise SystemExit('grid card not found')
n=section.find('<div class="card"><h4>KPI Tree Toy</h4>',m)
if n<0: raise SystemExit('kpi card marker not found')
card='''<div class="card radial-experiment"><h4>Radial System</h4><div class="radial-canvas-container"><canvas id="radial-canvas" aria-label="Interactive radial geometric system"></canvas><div class="radial-status"><span>●</span> <span id="radial-status-text">SYSTEM ACTIVE</span></div></div><div class="radial-controls"><p class="radial-copy">Derived from a radial geometric study explored in my identity work.</p><label>Frequency <input id="radial-frequency" type="range" min="6" max="64" value="32"><b id="radial-frequency-value">32</b></label><label>Amplitude <input id="radial-amplitude" type="range" min="0" max="50" value="10"><b id="radial-amplitude-value">10</b></label><button id="radial-break" type="button">BREAK RULE ↗</button></div></div>'''
section=section[:m]+card+section[n:]
s=s[:start]+section+s[end+10:]
css='''<style id="radial-v1-css">.radial-experiment{min-width:0}.radial-canvas-container{position:relative;width:100%;aspect-ratio:1/1;overflow:hidden;background:#0A0F15;border-radius:16px}.radial-canvas-container canvas{width:100%;height:100%;display:block}.radial-status{position:absolute;left:12px;bottom:10px;font:500 9px var(--fm);letter-spacing:.07em;text-transform:uppercase;color:var(--accent);pointer-events:none}.radial-status span:first-child{display:inline-block;filter:drop-shadow(0 0 6px #B9885F88)}.radial-status.broken{color:var(--stone)}.radial-controls{display:flex;flex-direction:column;gap:12px;margin-top:16px}.radial-copy{font:11px/1.55 var(--fb);color:var(--muted);margin:0 0 3px}.radial-controls label{font:9px var(--fm);letter-spacing:.05em;text-transform:uppercase;color:var(--stone)}.radial-controls input[type=range]{width:100%;margin-top:7px;accent-color:var(--accent)}.radial-controls label b{float:right;color:var(--accent);font-weight:500}.radial-controls button{border:0;background:none;padding:0;text-align:left;color:var(--accent);font:600 9px var(--fm);letter-spacing:.08em;text-transform:uppercase;cursor:pointer}.radial-controls button:hover{color:var(--ink)}.radial-controls button:disabled{opacity:.5;cursor:default}.radial-experiment.radial-broken .radial-canvas-container{background:#0A0D13}</style>'''
if 'id="radial-v1-css"' not in s: s=s.replace('</head>',css+'</head>',1)
js=r'''<script id="radial-v1-js">(function(){function init(){var c=document.getElementById('radial-canvas');if(!c)return;var w=c.parentElement,x=c.getContext('2d',{alpha:true}),f=document.getElementById('radial-frequency'),a=document.getElementById('radial-amplitude'),fv=document.getElementById('radial-frequency-value'),av=document.getElementById('radial-amplitude-value'),b=document.getElementById('radial-break'),st=document.getElementById('radial-status-text'),sd=document.querySelector('.radial-status'),dpr=1,W=1,H=1,ph=0,raf=0,run=false,broken=false,sys={f:+f.value,a:+a.value,s:.015,w:0},tar={f:sys.f,a:sys.a,s:.015,w:0};function resize(){var r=w.getBoundingClientRect();W=Math.max(1,r.width);H=Math.max(1,r.height);dpr=Math.min(devicePixelRatio||1,2);c.width=Math.round(W*dpr);c.height=Math.round(H*dpr);x.setTransform(dpr,0,0,dpr,0,0)}function lerp(q,e,t){return q+(e-q)*t}function draw(){if(!run)return;sys.f=lerp(sys.f,tar.f,.08);sys.a=lerp(sys.a,tar.a,.055);sys.s=lerp(sys.s,tar.s,.045);sys.w=lerp(sys.w,tar.w,.03);ph+=sys.s;x.fillStyle='rgba(10,15,21,.20)';x.fillRect(0,0,W,H);var cx=W/2,cy=H/2,base=Math.min(W,H)*.105;x.lineWidth=.65;x.strokeStyle='rgba(185,136,95,.34)';x.fillStyle='rgba(212,196,183,.92)';var n=Math.max(6,Math.min(64,sys.f));for(var r=1;r<=4;r++){var rad=base*r,prev=null;for(var i=0;i<n;i++){var ang=i*6.283185307/n,wv=Math.sin(ph+i*.5+r)*sys.a,noise=broken?(Math.sin(i*12.9898+r*78.233+ph*1.7)*.5-.25)*sys.w*8*r:0,rr=rad+wv+noise,px=cx+Math.cos(ang)*rr,py=cy+Math.sin(ang)*rr;if(prev&&!broken){x.beginPath();x.moveTo(prev.x,prev.y);x.lineTo(px,py);x.stroke()}x.beginPath();x.arc(px,py,1.7,0,6.283185307);x.fill();prev={x:px,y:py}}}raf=requestAnimationFrame(draw)}function start(){if(run)return;run=true;raf=requestAnimationFrame(draw)}function stop(){run=false;cancelAnimationFrame(raf)}f.oninput=function(){if(!broken){tar.f=+this.value;fv.textContent=this.value}};a.oninput=function(){if(!broken){tar.a=+this.value;av.textContent=this.value}};b.onclick=function(){if(broken)return;broken=true;b.disabled=true;b.textContent='RULE BROKEN';st.textContent='ANOMALY DETECTED';sd.classList.add('broken');w.parentElement.classList.add('radial-broken');sys.a=Math.min(170,Math.max(90,+a.value*7));sys.s=.18;tar.a=Math.min(34,+a.value*2.3);tar.s=.035;tar.w=2.2};if('IntersectionObserver' in window){new IntersectionObserver(function(es){es.forEach(function(e){if(e.isIntersecting)start();else stop()})},{threshold:.05}).observe(w)}else start();addEventListener('resize',resize,{passive:true});resize();x.fillStyle='#0A0F15';x.fillRect(0,0,W,H);start()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init()})();</script>'''
if 'id="radial-v1-js"' not in s: s=s.replace('</body>',js+'</body>',1)
s=re.sub(r'\(function\(\)\{var c=document\.getElementById\([\"\']cols[\"\']\).*?\}\)\(\);','',s,count=1)
p.write_text(s,encoding='utf-8')
